#############################################################################
# Makefile for building: raytracer-42
# Generated by qmake (2.01a) (Qt 4.6.3) on: Sat Apr 30 20:11:01 2011
# Project:  raytracer-42.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile raytracer-42.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc -Isrc/gui -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread -lSDL
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =	src/BoundingBox.cpp \
		src/Camera.cpp \
		src/CinemaCamera.cpp \
		src/Color.cpp \
		src/DirectLight.cpp \
		src/EquationSolver.cpp \
		src/Light.cpp \
		src/main.cpp \
		src/Material.cpp \
		src/Matrix.cpp \
		src/Object.cpp \
		src/ObjectPrimitive.cpp \
		src/Plan.cpp \
		src/Ray.cpp \
		src/Raytracer.cpp \
		src/RaytracerThread.cpp \
		src/RenderingConfiguration.cpp \
		src/RenderingInterface.cpp \
		src/Scene.cpp \
		src/Sphere.cpp \
		src/Spot.cpp \
		src/Texture.cpp \
		src/Vector.cpp \
		src/gui/gui.cpp \
		src/gui/guiAliasing.cpp \
		src/gui/guiAmbiantOcclusion.cpp \
		src/gui/guiDirectLight.cpp \
		src/gui/guiFlou.cpp \
		src/gui/guiLumiereDiffuse.cpp \
		src/gui/guiMenuBar.cpp \
		src/gui/guiPhotonMapping.cpp \
		src/gui/guiPutpixel.cpp \
		src/gui/guiReflection.cpp \
		src/gui/guiRendering.cpp \
		src/gui/guiSamplingMethod.cpp \
		src/gui/guiTransparence.cpp moc_gui.cpp
OBJECTS       =	BoundingBox.o \
		Camera.o \
		CinemaCamera.o \
		Color.o \
		DirectLight.o \
		EquationSolver.o \
		Light.o \
		main.o \
		Material.o \
		Matrix.o \
		Object.o \
		ObjectPrimitive.o \
		Plan.o \
		Ray.o \
		Raytracer.o \
		RaytracerThread.o \
		RenderingConfiguration.o \
		RenderingInterface.o \
		Scene.o \
		Sphere.o \
		Spot.o \
		Texture.o \
		Vector.o \
		gui.o \
		guiAliasing.o \
		guiAmbiantOcclusion.o \
		guiDirectLight.o \
		guiFlou.o \
		guiLumiereDiffuse.o \
		guiMenuBar.o \
		guiPhotonMapping.o \
		guiPutpixel.o \
		guiReflection.o \
		guiRendering.o \
		guiSamplingMethod.o \
		guiTransparence.o \
		moc_gui.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		raytracer-42.pro
QMAKE_TARGET  = raytracer-42
DESTDIR       = 
TARGET        = raytracer-42

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: raytracer-42.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile raytracer-42.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile raytracer-42.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/raytracer-421.0.0 || $(MKDIR) .tmp/raytracer-421.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/raytracer-421.0.0/ && $(COPY_FILE) --parents src/BoundingBox.hpp src/Camera.hpp src/CinemaCamera.hpp src/Color.hpp src/DirectLight.hpp src/EquationSolver.hpp src/Light.hpp src/Material.hpp src/Matrix.hpp src/Object.hpp src/ObjectPrimitive.hpp src/Plan.hpp src/Point.hpp src/Ray.hpp src/Raytracer.hpp src/RaytracerThread.hpp src/RenderingConfiguration.hpp src/RenderingInterface.hpp src/Rotation.hpp src/Scene.hpp src/Sphere.hpp src/Spot.hpp src/Texture.hpp src/Vector.hpp src/gui/gui.hpp .tmp/raytracer-421.0.0/ && $(COPY_FILE) --parents configure_options/endian.c src/BoundingBox.cpp src/Camera.cpp src/CinemaCamera.cpp src/Color.cpp src/DirectLight.cpp src/EquationSolver.cpp src/Light.cpp src/main.cpp src/Material.cpp src/Matrix.cpp src/Object.cpp src/ObjectPrimitive.cpp src/Plan.cpp src/Ray.cpp src/Raytracer.cpp src/RaytracerThread.cpp src/RenderingConfiguration.cpp src/RenderingInterface.cpp src/Scene.cpp src/Sphere.cpp src/Spot.cpp src/Texture.cpp src/Vector.cpp src/gui/gui.cpp src/gui/guiAliasing.cpp src/gui/guiAmbiantOcclusion.cpp src/gui/guiDirectLight.cpp src/gui/guiFlou.cpp src/gui/guiLumiereDiffuse.cpp src/gui/guiMenuBar.cpp src/gui/guiPhotonMapping.cpp src/gui/guiPutpixel.cpp src/gui/guiReflection.cpp src/gui/guiRendering.cpp src/gui/guiSamplingMethod.cpp src/gui/guiTransparence.cpp .tmp/raytracer-421.0.0/ && (cd `dirname .tmp/raytracer-421.0.0` && $(TAR) raytracer-421.0.0.tar raytracer-421.0.0 && $(COMPRESS) raytracer-421.0.0.tar) && $(MOVE) `dirname .tmp/raytracer-421.0.0`/raytracer-421.0.0.tar.gz . && $(DEL_FILE) -r .tmp/raytracer-421.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gui.cpp
moc_gui.cpp: src/RenderingInterface.hpp \
		src/Color.hpp \
		src/gui/gui.hpp
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/gui.hpp -o moc_gui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

endian.o: configure_options/endian.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o endian.o configure_options/endian.c

BoundingBox.o: src/BoundingBox.cpp src/BoundingBox.hpp \
		src/Vector.hpp \
		src/Point.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BoundingBox.o src/BoundingBox.cpp

Camera.o: src/Camera.cpp src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera.o src/Camera.cpp

CinemaCamera.o: src/CinemaCamera.cpp src/CinemaCamera.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CinemaCamera.o src/CinemaCamera.cpp

Color.o: src/Color.cpp src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Color.o src/Color.cpp

DirectLight.o: src/DirectLight.cpp src/DirectLight.hpp \
		src/Light.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Color.hpp \
		src/Ray.hpp \
		src/RenderingConfiguration.hpp \
		src/Object.hpp \
		src/Rotation.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DirectLight.o src/DirectLight.cpp

EquationSolver.o: src/EquationSolver.cpp src/EquationSolver.hpp \
		src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EquationSolver.o src/EquationSolver.cpp

Light.o: src/Light.cpp src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Light.o src/Light.cpp

main.o: src/main.cpp src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp \
		src/CinemaCamera.hpp \
		src/Sphere.hpp \
		src/Spot.hpp \
		src/Plan.hpp \
		src/gui/gui.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Material.o: src/Material.cpp src/Material.hpp \
		src/Texture.hpp \
		src/Color.hpp \
		src/Vector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Material.o src/Material.cpp

Matrix.o: src/Matrix.cpp src/Matrix.hpp \
		src/Vector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Matrix.o src/Matrix.cpp

Object.o: src/Object.cpp src/Object.hpp \
		src/Vector.hpp \
		src/Point.hpp \
		src/Rotation.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Material.hpp \
		src/Texture.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Object.o src/Object.cpp

ObjectPrimitive.o: src/ObjectPrimitive.cpp src/ObjectPrimitive.hpp \
		src/Vector.hpp \
		src/Point.hpp \
		src/Rotation.hpp \
		src/BoundingBox.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Material.hpp \
		src/Texture.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectPrimitive.o src/ObjectPrimitive.cpp

Plan.o: src/Plan.cpp src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp \
		src/Plan.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plan.o src/Plan.cpp

Ray.o: src/Ray.cpp src/Ray.hpp \
		src/Color.hpp \
		src/Point.hpp \
		src/Vector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ray.o src/Ray.cpp

Raytracer.o: src/Raytracer.cpp src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Raytracer.o src/Raytracer.cpp

RaytracerThread.o: src/RaytracerThread.cpp src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RaytracerThread.o src/RaytracerThread.cpp

RenderingConfiguration.o: src/RenderingConfiguration.cpp src/RenderingConfiguration.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderingConfiguration.o src/RenderingConfiguration.cpp

RenderingInterface.o: src/RenderingInterface.cpp src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RenderingInterface.o src/RenderingInterface.cpp

Scene.o: src/Scene.cpp src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o src/Scene.cpp

Sphere.o: src/Sphere.cpp src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Rotation.hpp \
		src/Ray.hpp \
		src/Color.hpp \
		src/Object.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Light.hpp \
		src/RenderingConfiguration.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp \
		src/Sphere.hpp \
		src/EquationSolver.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sphere.o src/Sphere.cpp

Spot.o: src/Spot.cpp src/Spot.hpp \
		src/Light.hpp \
		src/Point.hpp \
		src/Vector.hpp \
		src/Color.hpp \
		src/Ray.hpp \
		src/RenderingConfiguration.hpp \
		src/Object.hpp \
		src/Rotation.hpp \
		src/ObjectPrimitive.hpp \
		src/BoundingBox.hpp \
		src/Material.hpp \
		src/Texture.hpp \
		src/Raytracer.hpp \
		src/Scene.hpp \
		src/Camera.hpp \
		src/RenderingInterface.hpp \
		src/RaytracerThread.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Spot.o src/Spot.cpp

Texture.o: src/Texture.cpp src/Texture.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture.o src/Texture.cpp

Vector.o: src/Vector.cpp src/Vector.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vector.o src/Vector.cpp

gui.o: src/gui/gui.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp \
		src/RenderingConfiguration.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o src/gui/gui.cpp

guiAliasing.o: src/gui/guiAliasing.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiAliasing.o src/gui/guiAliasing.cpp

guiAmbiantOcclusion.o: src/gui/guiAmbiantOcclusion.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiAmbiantOcclusion.o src/gui/guiAmbiantOcclusion.cpp

guiDirectLight.o: src/gui/guiDirectLight.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiDirectLight.o src/gui/guiDirectLight.cpp

guiFlou.o: src/gui/guiFlou.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiFlou.o src/gui/guiFlou.cpp

guiLumiereDiffuse.o: src/gui/guiLumiereDiffuse.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiLumiereDiffuse.o src/gui/guiLumiereDiffuse.cpp

guiMenuBar.o: src/gui/guiMenuBar.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiMenuBar.o src/gui/guiMenuBar.cpp

guiPhotonMapping.o: src/gui/guiPhotonMapping.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiPhotonMapping.o src/gui/guiPhotonMapping.cpp

guiPutpixel.o: src/gui/guiPutpixel.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiPutpixel.o src/gui/guiPutpixel.cpp

guiReflection.o: src/gui/guiReflection.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiReflection.o src/gui/guiReflection.cpp

guiRendering.o: src/gui/guiRendering.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiRendering.o src/gui/guiRendering.cpp

guiSamplingMethod.o: src/gui/guiSamplingMethod.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiSamplingMethod.o src/gui/guiSamplingMethod.cpp

guiTransparence.o: src/gui/guiTransparence.cpp src/gui/gui.hpp \
		src/RenderingInterface.hpp \
		src/Color.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guiTransparence.o src/gui/guiTransparence.cpp

moc_gui.o: moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gui.o moc_gui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

