######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 26 14:37:40 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.hpp
SOURCES += main.cpp
