######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 29 14:39:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gui.hpp Scene.hpp window.hpp
SOURCES += gui.cpp main.cpp
