##
## Makefile for  in /home/jochau_g//Desktop/rt/raytracer-42
## 
## Made by gael jochaud-du-plessix
## Login   <jochau_g@epitech.net>
## 
## Started on  Tue Apr 26 10:53:44 2011 gael jochaud-du-plessix
## Last update Tue Apr 26 10:53:49 2011 gael jochaud-du-plessix
##

all: test