##
## Makefile for  in /home/jochau_g//dev/c/raytracer/raytracer-42
## 
## Made by gael jochaud-du-plessix
## Login   <jochau_g@epitech.net>
## 
## Started on  Fri Apr 29 10:25:57 2011 gael jochaud-du-plessix
## Last update Fri Apr 29 10:26:30 2011 gael jochaud-du-plessix
##

all:
	gcc -W -Wall endian.c -o endian

clean:
	rm -f endian